name: build.yml
on:
  workflow_dispatch:
  schedule:
    - cron: "30 3,9,21 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Checkout runetfreedom/geodat2srs
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/geodat2srs
          path: geodat2srs

      - name: Checkout v2fly/domain-list-community
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community

      - name: Checkout runetfreedom/domain-list-custom
        uses: actions/checkout@v4
        with:
          repository: runetfreedom/domain-list-custom
          path: domain-list-custom

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./geodat2srs/go.mod
          cache: false

      - name: Enable swap for build
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Prepare custom geosite data
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-data
          while IFS= read -r list || [[ -n "$list" ]]; do
            [[ -z "$list" || "$list" =~ ^# ]] && continue
            cp "./domain-list-community/data/${list}" "./tmp/geosite-data/"
          done < ./scripts/geosite-dlc-lists.txt
          cp ./custom-lists/* ./tmp/geosite-data/
        shell: bash

      - name: Build custom geoip.dat
        run: |
          set -euo pipefail
          mkdir -p ./publish
          go run github.com/v2fly/geoip@latest -c ./geoip-config.json
          sha256sum ./publish/geoip.dat > ./publish/geoip.dat.sha256sum

      - name: Build domain-list-custom binary
        working-directory: domain-list-custom
        run: |
          set -euo pipefail
          go mod download
          go build -v -o ../dlc-builder ./

      - name: Build geosite ru-core
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-ru-core
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-ru-core.dat \
            --exportlists=category-ru-core \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-ru-core

      - name: Build geosite category-gov-ru
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-gov
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-category-gov-ru.dat \
            --exportlists=category-gov-ru \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-gov

      - name: Build geosite mailru
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-mailru
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-mailru.dat \
            --exportlists=mailru \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-mailru

      - name: Build geosite ok
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-ok
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-ok.dat \
            --exportlists=ok \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-ok

      - name: Build geosite ozon
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-ozon
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-ozon.dat \
            --exportlists=ozon \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-ozon

      - name: Build geosite vk
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-vk
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-vk.dat \
            --exportlists=vk \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-vk

      - name: Build geosite x5
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-x5
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-x5.dat \
            --exportlists=x5 \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-x5

      - name: Build geosite yandex
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-yandex
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-yandex.dat \
            --exportlists=yandex \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-yandex

      - name: Build geosite core lists
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-core
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-core.dat \
            --exportlists=category-media-ru,twitch,youtube,category-streaming-ru,category-bank-ru,category-torrent,okko,steam,category-gaming-mmo,category-gaming-4game,trovo,win-update,telegram-cdn \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-core

      - name: Build geosite ru-all
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-ru-all
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-ru-all.dat \
            --exportlists=ru-all \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-ru-all

      - name: Build geosite ads
        run: |
          set -euo pipefail
          mkdir -p ./tmp/geosite-output-ads
          ./dlc-builder \
            --datapath=./tmp/geosite-data \
            --datname=geosite-ads.dat \
            --exportlists=category-ads-all,google-ads,xiaomi-ads,bytedance-ads,tencent-ads \
            --togfwlist= \
            --outputpath=./tmp/geosite-output-ads

      - name: Merge geosite dat files
        working-directory: tools/v2dat-lite
        run: |
          set -euo pipefail
          mkdir -p ../../publish
          go run . -o ../../publish/geosite.dat \
            ../../tmp/geosite-output-ru-core/geosite-ru-core.dat \
            ../../tmp/geosite-output-gov/geosite-category-gov-ru.dat \
            ../../tmp/geosite-output-mailru/geosite-mailru.dat \
            ../../tmp/geosite-output-ok/geosite-ok.dat \
            ../../tmp/geosite-output-ozon/geosite-ozon.dat \
            ../../tmp/geosite-output-vk/geosite-vk.dat \
            ../../tmp/geosite-output-x5/geosite-x5.dat \
            ../../tmp/geosite-output-yandex/geosite-yandex.dat \
            ../../tmp/geosite-output-core/geosite-core.dat \
            ../../tmp/geosite-output-ru-all/geosite-ru-all.dat \
            ../../tmp/geosite-output-ads/geosite-ads.dat
          sha256sum ../../publish/geosite.dat > ../../publish/geosite.dat.sha256sum

      - name: Generate sing-box srs
        run: |
          go build -C geodat2srs ./
          ./geodat2srs/geodat2srs geoip -i ./publish/geoip.dat -o ./tmp/sing-box/rule-set-geoip/
          ./geodat2srs/geodat2srs geosite -i ./publish/geosite.dat -o ./tmp/sing-box/rule-set-geosite/
          cd ./tmp/sing-box || exit 1
          zip -r ../../publish/sing-box.zip *

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
          file_glob: true
          file: ./publish/*

      - name: Git push assets to "release" branch
        run: |
          rm -rf ./publish/sing-box.zip
          mv ./tmp/sing-box ./publish/sing-box
          cd publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Disable swap
        if: always()
        run: |
          sudo swapoff /swapfile
          sudo rm -f /swapfile
